services:
  event-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event-service
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    depends_on:
      - db
    environment:
      - DB_URL=postgresql+asyncpg://postgres:postgres@event-db:5432/event_db
    networks:
      - attendance_net

  db:
    image: postgres:15
    container_name: event-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - attendance_net

volumes:
  postgres_data:

networks:
  attendance_net:
    external: true