"""'Init4'

Revision ID: 820056fd2c76
Revises: efcf4b56f37b
Create Date: 2025-05-17 13:59:32.345998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '820056fd2c76'
down_revision: Union[str, None] = 'efcf4b56f37b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'event_templates', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_templates', type_='unique')
    # ### end Alembic commands ###
