"""'Init3'

Revision ID: efcf4b56f37b
Revises: ed1bde3380cd
Create Date: 2025-05-17 13:49:58.675800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efcf4b56f37b'
down_revision: Union[str, None] = 'ed1bde3380cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_templates', 'owner_id')
    op.add_column('events', sa.Column('owner_id', sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'owner_id')
    op.add_column('event_templates', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
